apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: tsopenshift443
  namespace: kic
spec:
  virtualServerAddress: "172.16.2.65"
  virtualServerPort: 443
  virtualServerName: openshift
  mode: performance
  snat: auto
  pool:
    service: nginx-ingress-nginx-ingress
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10
