apiVersion: v1 
kind: ConfigMap 
metadata:
  name: nginx-api-conf
  namespace: {{ .Release.Namespace }} 
data:
  api.conf: |-

    server {
      listen {{ .Values.configmapAPI.APIPort }};
      server_name {{ .Values.configmapAPI.APIHostname }};
      location /api {
        api write=on;
        allow {{ .Values.configmapAPI.AllowCIDR }}; 
        deny all;
      }
      location /dashboard.html {
        root /usr/share/nginx/html;
      }
      location = /metrics {
        js_content prometheus.metrics;
      }
      location = /health-mcgw { 
        default_type text/plain;
        return 200 "healthy\n";
      }
      access_log off;
    }
