apiVersion: v1 
kind: ConfigMap 
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |-
    #user nginx;
    worker_processes auto;
    load_module modules/ngx_http_js_module.so;
    load_module modules/ndk_http_module.so;
    load_module modules/ngx_http_lua_module.so;
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;
        sendfile on;
        #tcp_nopush on; gzip on;
        keepalive_timeout 65;
        js_import mcgw from conf.d/mcgw.js;
        js_import /usr/share/nginx-plus-module-prometheus/prometheus.js;
        include /etc/nginx/conf.d/*.conf;
    }
