apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginxmcgw.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcgw.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mcgw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "nginxmcgw.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: api
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health-mcgw
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
                               
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: nginx-default-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: nginx-api-conf
            mountPath: /etc/nginx/conf.d/api.conf
            subPath: api.conf
          - name: mcgw-js
            mountPath: /etc/nginx/conf.d/mcgw.js
            subPath: mcgw.js
          - name: mcgw-conf
            mountPath: /etc/nginx/conf.d/mcgw.conf
            subPath: mcgw.conf

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-default-conf
        configMap:
          name: nginx-default-conf
      - name: nginx-api-conf
        configMap:
          name: nginx-api-conf
      - name: mcgw-conf
        configMap:
          name: mcgw-conf
      - name: mcgw-js
        configMap:
          name: mcgw-js

      serviceAccountName: mcgwsa
      serviceAccount: mcgwsa
