{{- range .Values.ingress.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ingresses.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .cert }}
  tls.key: {{ .key }}
{{- end }}
